### ISSUE TITLE
In Figure 3 Audio Elements should hold codec config IDs.

### ISSUE THREAD

**Issue by yeroro** [AOMediaCodec/iamf#306] opened 2023-03-06 14:18 UTC
In Figure 3 in §[3.2.2](https://aomediacodec.github.io/iamf/#data), it currently shows the Codec Configs holding audio element IDs. It should be the other way around.

**Comment by jwcullen** [comment] 2023-03-06 15:00
Duplicate of #275

**Closed as completed** 2023-03-20 19:56 UTC
Labels: duplicate
